<?php

use Magento\Framework\App\Action\Action;

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$mode = 'grid';
$items = $block->getProductCollection();
if ($items && $items->getSize()) : ?>
    <div class="block-content mp-product-slider-content">
        <div class="products-<?= /** @noEscape */  $mode ?> <?= /** @noEscape */  $mode ?>">
            <ol class="product-items widget-viewed-grid">
                <?php $iterator = 1; ?>
                <div id="mp-list-items" class="owl-carousel owl-theme">
                    <?php foreach ($items as $_item) : ?>
                        <?= ($iterator++ == 1) ? '<li class="product-item product-slider"">' : '</li><li class="product-item product-slider"">' ?>
                        <div class="slider-product-item-info">
                            <a href="<?= /* @escapeNotVerified */ $_item->getProductUrl() ?>"
                               class="product photo slider-product-item-photo">
                                <?php echo $block->absblock->getImage($_item,'category_page_grid')->toHtml(); ?>
                            </a>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="<?= /* @escapeNotVerified */ $_helper->productAttribute($_item, $_item->getName(), 'name') ?>"
                                       href="<?= /* @escapeNotVerified */ $_item->getProductUrl() ?>">
                                        <?= /* @escapeNotVerified */ $_helper->productAttribute($_item, $_item->getName(), 'name') ?>
                                    </a>
                                </strong>

                                <?= $block->absblock->getReviewsSummaryHtml($_item,'short',true) ?>
                        		<?= /* @escapeNotVerified */ $block->absblock->getProductPrice($_item) ?>

                                <div class="product actions slider-product-item-actions product-item-actions">
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()) : ?>
                                                <?php $postParams = $block->absblock->getAddToCartPostParams($_item); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
		                                            <?= $block->absblock->getBlockHtml('formkey') ?>
		                                            <button type="submit"
		                                                    title="<?= __('Add to Cart') ?>"
		                                                    class="action tocart primary">
		                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
		                                            </button>
                                                </form>
                                            <?php else : ?>
                                                <?php if ($_item->getIsSalable()) : ?>
                                                    <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else : ?>
                                                    <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary">
		                                    <?php if ($addToBlock = $block->absblock->getChildBlock('addto')): ?>
		                                        <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
		                                    <?php endif; ?>
	                                	</div>
 
                                </div>
                            </div>
                        </div>
                        <?= ($iterator === count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </div>
            </ol>
        </div>
        <?= $block->getPagerHtml() ?>
    </div>
    <script>
    (function () {
        require(["jquery", "ecommistry/productlist/owl.carousel"], function ($) {
            $(document).ready(function () {
                $("#mp-list-items").owlCarousel({
                    navigation: true, 
                    autoPlay: true,
                    loop: false, 
                    items: 4
                });
            });
        });
    })();
</script>
<?php endif; ?>

